### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by pkraison** [saic-vul/fbrs_interactive_segmentation#1]
I'm getting an error while running the demo.py
ImportError: cannot import name 'Optional'. any help would be appreciated, thanks!

**Comment by ksofiyuk** [comment]
You probably have a version of Python less than 3.6. Upgrade the interpreter to version 3.6+.

**Comment by pkraison** [comment]
I have python 3.6.10. but I solved it by downgrading torchvision from 0.5.0 to 0.4.0. and it's working now. Thanks for your response. can't we change version of torchvision >=0.5.0 to  >=0.4.0. thanks a lot for your response. :+1:
