### ISSUE TITLE
fbrs_interactive_segmentation.ipynb

### ISSUE THREAD

**Issue by AlexRMU** [saic-vul/fbrs_interactive_segmentation#10]
Your colab doesn't work on its own and I changed it.
https://colab.research.google.com/gist/AlexRMU/1cedcc342e8cdec7bc8881007db77f4a/fbrs_interactive_segmentation.ipynb#scrollTo=7jDwxuLkHkRy
And received
`float division by zero`

**Comment by AlexRMU** [comment]
"work on its" own means that the user does not have to download or transfer anything, but just click and everything will work

**Comment by ptrvilya** [comment]
The error is caused by the incorrect path to datasets, you are trying to evaluate the model on GrabCut dataset and download it to `./datasets/InteractiveSegmentation/GrabCut` (relative to folder with cloned repository), but the default path in `config.yml` is absolute, starting from root: `/datasets/InteractiveSegmentation/GrabCut`. You just have to change the default path and everything will work.

**Comment by AlexRMU** [comment]
Launched your colab. An error appears at the very beginning:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-0bc6b562c85d> in <module>()
     11 
     12 sys.path.insert(0, '..')
---> 13 from isegm.utils import vis, exp
     14 
     15 from isegm.inference import utils

ModuleNotFoundError: No module named 'isegm'
```
And: `cfg = exp.load_config_file('../config.yml', return_edict=True)`
You refer to config.yml, but it is not downloaded! Why? Then I added to the beginning:
```
!git clone https://github.com/saic-vul/fbrs_interactive_segmentation
%cd fbrs_interactive_segmentation
!pip install -r requirements.txt
```
It work. Further
In Init model:
```
AssertionError                            Traceback (most recent call last)
<ipython-input-10-95614765a096> in <module>()
      4 MODEL_THRESH = 0.49
      5 
----> 6 checkpoint_path = utils.find_checkpoint(cfg.INTERACTIVE_MODELS_PATH, 'resnet34_dh128_sbd')
      7 model = utils.load_is_model(checkpoint_path, device)
      8 

/content/fbrs_interactive_segmentation/isegm/inference/utils.py in find_checkpoint(weights_folder, checkpoint_name)
    171     else:
    172         model_checkpoints = list(model_folder.rglob(f'{checkpoint_name}*.pth'))
--> 173         assert len(model_checkpoints) == 1
    174         checkpoint_path = model_checkpoints[0]
    175 

AssertionError: 
```
Where /weights? Where /experiments? After all, how are you going to do Interactive Segmentation on the command line? (Mb https://github.com/davidbau/rewriting)

**Comment by ksofiyuk** [comment]
> Launched your colab.

We didn't provide any colab. We provided only jupyter notebook, which we ran on a local machine with Jupyter Server.

> Where /weights? Where /experiments? After all, how are you going to do Interactive Segmentation on the command line? (Mb https://github.com/davidbau/rewriting) 
You can find information about how to set up paths in the [Training section](https://github.com/saic-vul/fbrs_interactive_segmentation#training) of our readme. Please read the [README](https://github.com/saic-vul/fbrs_interactive_segmentation/blob/master/README.md) carefully before asking questions.
