### ISSUE TITLE
How to train DAVIS datasets?

### ISSUE THREAD

**Issue by Andy-zhujunwen** [saic-vul/fbrs_interactive_segmentation#12]

**Comment by ptrvilya** [comment]
If you want to train on any dataset you have to implement a dataset class similar to [SBDDataset](https://github.com/saic-vul/fbrs_interactive_segmentation/blob/c3f579016f7bd1e0f358cb680a8365ccb6f22b6b/isegm/data/sbd.py#L12), and use it in the training script [here](https://github.com/saic-vul/fbrs_interactive_segmentation/blob/c3f579016f7bd1e0f358cb680a8365ccb6f22b6b/models/sbd/r34_dh128.py#L88).
