### ISSUE TITLE
could be used as an annotation tool for instance segmentation?

### ISSUE THREAD

**Issue by AllenDun** [saic-vul/fbrs_interactive_segmentation#13]
great work. It could be used as an annotation tool for instance segmentation, since the fbrs greatly speeds up the interactive segmentation? If so, it would  be very useful. Thanks

**Comment by ksofiyuk** [comment]
Of course, you can try our interactive demo for that purpose. It supports segmentation of multiple objects in one image.

**Comment by DanielFlash** [comment]
I have only one object on image and it is segmented by one click. After that I press "space" or "finish object" and save its mask, but when I open the saved mask from explorer it is just a black image. What I am doing wrong? Thanks

**Comment by ptrvilya** [comment]
Please refer to this [issue](https://github.com/saic-vul/fbrs_interactive_segmentation/issues/17), @ksofiyuk has written about mask saving there.
