### ISSUE TITLE
can this be implemented for video tracking.

### ISSUE THREAD

**Issue by priydarshi1o1** [saic-vul/fbrs_interactive_segmentation#15]
For sequence dataset(video) can we use this interactive segmentation for using previously segmented objects in previous frames.

**Comment by ksofiyuk** [comment]
You can use our algorithm to get objects masks for the first frame. Then you can try to use some sort of tracking with segmentation algorithms (e.g. [MOTS: Multi-Object Tracking and Segmentation](https://arxiv.org/abs/1902.03604)).

**Comment by priydarshi1o1** [comment]
Thanks for your reply, although MOTS authors have provided scripts for traning for semi-interactive annotation they haven't provided anything.
