### ISSUE TITLE
Where is the SBD validation set?

### ISSUE THREAD

**Issue by sdfghjkyuio** [saic-vul/fbrs_interactive_segmentation#16]
I downloaded SBD and its corresponding train set list, but I can't find its validation set list.

**Comment by ksofiyuk** [comment]
If you download SBD dataset from [this](http://www.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/semantic_contours/benchmark.tgz) link, you can find the list of validation images by the path `benchmark_RELEASE/dataset/val.txt` after unpacking the archive.

**Comment by sdfghjkyuio** [comment]
Thank you!
