### ISSUE TITLE
Saving mask doesn't work

### ISSUE THREAD

**Issue by sdfghjkyuio** [saic-vul/fbrs_interactive_segmentation#17]
I run demo.py and segment a picture, and then I click 'save mask'. But the saved mask picture is all black with out mask.
![20190810_10026](https://user-images.githubusercontent.com/67036136/86724169-2267b400-c05b-11ea-9b50-17a3cb419db4.png)

**Comment by pkraison** [comment]
check whether it's generating right points

**Comment by sdfghjkyuio** [comment]
Could you tell me the meaning of right points? I forget where it has been mentioned. Thank you!

**Comment by ksofiyuk** [comment]
Before saving the mask you must finish an object (by pressing <Space>, for instance), otherwise the current mask won't be saved.

**Comment by ksofiyuk** [comment]
In addition, our demo saves masks with object ids (1,  2, 3 and so on) within PNGs, it means that the first object will have (1, 1, 1) color, not (255, 255, 255). So in image viewers it's almost visually indistinguishable.

**Comment by sdfghjkyuio** [comment]
I can understand it now. Thanks!!
