### ISSUE TITLE
training config on COCO + LVIS

### ISSUE THREAD

**Issue by XavierCHEN34** [saic-vul/fbrs_interactive_segmentation#19]
Hello, could you please release your training config for COCO + LVIS, I trained on coco+lvis but got much worse performance than yours. I directly concated the two dataset with torch.utils.data.ConcatDataset. And  trained the model for 12 epoches, the @80 @85  is even worse than the model trained on SBD.

**Comment by ptrvilya** [comment]
Hi, thanks for your interest! Unfortunately we can't share the details now.

**Comment by brianlai98** [comment]
@ptrvilya Would it be okay to share the details now?

**Comment by ptrvilya** [comment]
@brianlai98 HI! Checkout our new paper here https://github.com/saic-vul/ritm_interactive_segmentation . We propose the model that is free of test-time optimization techniques and sets SotA results. The new model is trained on COCO+LVIS.
