### ISSUE TITLE
Some controls are missing on mac os in GUI (?)

### ISSUE THREAD

**Issue by arogozhnikov** [saic-vul/fbrs_interactive_segmentation#2]
Here is a screenshot of how it appears to me. 

<img width="1102" alt="Screen Shot 2020-02-21 at 12 29 45 AM" src="https://user-images.githubusercontent.com/6318811/75017208-6dcd4d00-5441-11ea-8197-ef7702839aff.png">

**Comment by ptrvilya** [comment]
We have tested GUI on Ubuntu 18.04 with tkinter.TkVersion 8.6. Problems on MacOS may encounter due to issues with Apple-supplied Tcl/Tk (refer to https://www.python.org/download/mac/tcltk/).

**Comment by arogozhnikov** [comment]
@ptrvilya thanks for response! 
I use brew-provided python, but still that looks like most probable reason (since tkinter says it uses 8.5). Unfortunately can't verify your guess in details.

**Comment by ptrvilya** [comment]
@arogozhnikov I've fixed the problem with menu in the latest commit, now all buttons should be visible (thanks to @vguzov for help with testing on MacOS).
