### ISSUE TITLE
click based Bounding Box generation.

### ISSUE THREAD

**Issue by aiwithshekhar** [saic-vul/fbrs_interactive_segmentation#26]
Hi maybe my question is not relevant to this code base.

Can this repo with code modifications used for click based Bounding Box generation.

**Comment by ptrvilya** [comment]
Hi, I think that the simplest option is to obtain bounding box from predicted segmentation mask.

**Comment by aiwithshekhar** [comment]
Thanks a lot for replying,
1) If i want to train SSD considering bounding box from fbrs segmentation mask as Ground truth and SSD output as prediction and trying to minimize the loss. Will this work?
2) Can i continue with the multipoint sampler for this?
