### ISSUE TITLE
multi object segmentation

### ISSUE THREAD

**Issue by shiragit** [saic-vul/fbrs_interactive_segmentation#28]
Hi, does this model supports multi object segmentation in a single frame? 
10x

**Comment by chamecall** [comment]
++

**Comment by chamecall** [comment]
> Hi, does this model supports multi object segmentation in a single frame?
> 10x

@shiragit , Have you achieved a solution to the problem of segmenting multiple objects

**Comment by ptrvilya** [comment]
Hi! The model supports segmentation of multiple objects, though it's an unnatural use case. The model was trained on at most two merged objects masks (e.g. [this lines](https://github.com/saic-vul/fbrs_interactive_segmentation/blob/f026fdc82474b8aaa6fa18aaa4a95ad9c507cd26/models/sbd/r34_dh128.py#L86)), so selecting each object separately should work better. The interface for multiple objects segmentation on one image  is implemented in our demo: "finish object" button adds the current mask to all instance masks for the current image and resets the model so you can start a new prediction from scratch.

**Comment by chamecall** [comment]
@ptrvilya, do you mean it's possible to get segmentations for multiple objects in one forward pass, not sequentially for each object?

**Comment by chamecall** [comment]
@ptrvilya, maybe there are some ways to increase performance in comparison with the method when we sequentially pass the points of each object to the network?

**Comment by ptrvilya** [comment]
@chamecall 
> do you mean it's possible to get segmentation for multiple objects in one forward pass, not sequentially for each object?
As I saw in your demo you don't pass object points of previous objects (object that was selected before clicking "finish object") but only current one so for each object you need to re-run network.

No, if you want to predict separate masks for different objects you have to re-run the network. 

> maybe there are some ways to increase performance in comparison with the method when we sequentially pass the points of each object to the network?

Theoretically you can combine clicks for different objects and perform a batched forward pass, but in that case you should have crops of exact same size so the Zoom-In implementation is to be changed. If you need to interact with multiple objects simultaneously you can also implement some sort of context switching, i.e. store runtime parameters for multiple objects and switch between them when the user changes an object.
