### ISSUE TITLE
Clicks for different classes.

### ISSUE THREAD

**Issue by chamecall** [saic-vul/fbrs_interactive_segmentation#30]
Сan I transfer to the network marks belonging to different objects, and not to signle one?

**Comment by chamecall** [comment]
May it possibly pass clicks of different objects in batch?

**Comment by chamecall** [comment]
Is it possible to forward image once and then pass different set of points multiple times?

**Comment by ksofiyuk** [comment]
> Сan I transfer to the network marks belonging to different objects, and not to signle one?

Sorry, I'm not sure I understand what you mean. A batch can contain different images and if you want to segment simultaneously different objects from one image, you can construct a batch that contains copies of the same image with points for different objects.

> May it possibly pass clicks of different objects in batch?

Yes, it is possible if you form a batch with copies of an image as I mentioned it above.

> Is it possible to forward image once and then pass different set of points multiple times?

No, it isn't possible. If your batch contain only one image (batchsize=1), you can pass points only for one object.
