### ISSUE TITLE
torch.hub.load(GLUON_RESNET_TORCH_HUB, 'gluon_resnet34_v1b', pretrained=True) not work in windows 10

### ISSUE THREAD

**Issue by happyCodingSusan** [saic-vul/fbrs_interactive_segmentation#32]
Does anybody know how to make torch.hub.load work in windows 10? Thanks

**Comment by Looottch** [comment]
> hub.lo

Hi, Have you make GLUON_RESNET_TORCH_HUB work in windows 10? Thanks in advance.

**Comment by Looottch** [comment]
> Does anybody know how to make torch.hub.load work in windows 10? Thanks

Hi, Have you make GLUON_RESNET_TORCH_HUB work in windows 10? Thanks in advance.
