### ISSUE TITLE
Could you share the training code on "COCO+LVIS" dataset?

### ISSUE THREAD

**Issue by JessLittle-art** [saic-vul/fbrs_interactive_segmentation#38]
It seems the performance of the model trained on "COCO+LVIS" dataset is much better than that on "SBD". Just wonder if you could share the training code on "COCO+LVIS" dataset? Many thanks.

**Comment by ptrvilya** [comment]
Hi! Checkout our new paper here https://github.com/saic-vul/ritm_interactive_segmentation . We propose the model that is free of test-time optimization techniques and sets SotA results.
