### ISSUE TITLE
Can i use the pretrained model without the GUI?

### ISSUE THREAD

**Issue by humzaahmad906** [saic-vul/fbrs_interactive_segmentation#4]

**Comment by ptrvilya** [comment]
Yes, checkout [Evaluation](https://github.com/saic-vul/fbrs_interactive_segmentation#evaluation) section of readme and [jupyter notebook](https://github.com/saic-vul/fbrs_interactive_segmentation/blob/master/notebooks/test_any_model.ipynb) for details.

**Comment by humzaahmad906** [comment]
Yes but if i'm passing custom images here like
--------------------------------------------------------------------------------------------------------------------------
clicks_list, ious_arr, pred = evaluate_sample(cv2.imread("example.jpg"), cv2.imread("1.jpg", cv2.IMREAD_GRAYSCALE), predictor, 
                                              pred_thr=MODEL_THRESH, 
                                              max_iou_thr=TARGET_IOU, max_clicks=EVAL_MAX_CLICKS)
--------------------------------------------------------------------------------------------------------------------------
Do i need to change something? Also can i use the evaluation process without giving it a mask?

**Comment by ptrvilya** [comment]
There are two options:
1. If you want to get NoC metric value you have to pass gt mask to ```evaluate_sample``` as in this mode user clicks are generated automatically with a certain strategy (refer to the paper for details).
2. If you want to get a predicted mask for the image with custom clicks you have to pass user clicks to a predictor (see [lines 28 - 57](https://github.com/saic-vul/fbrs_interactive_segmentation/blob/8a298a468c543deab2c84095ff7d65de0f22c38d/interactive_demo/controller.py#L28) for an example). GUI is used here to ease the choosing of the next click, but this can be done manually without interface.
    
In both options image should be normalized before passing it to the network.

**Comment by humzaahmad906** [comment]
It helped alot. Thanks
