### ISSUE TITLE
Training it on custom dataset

### ISSUE THREAD

**Issue by humzaahmad906** [saic-vul/fbrs_interactive_segmentation#6]
I want to train the given network on my own dataset. What steps do i need to follow?

**Comment by ptrvilya** [comment]
You have to define dataset class for your data (see [SBDDataset](https://github.com/saic-vul/fbrs_interactive_segmentation/blob/master/isegm/data/sbd.py) for an example) and then create a model training script for your dataset (see [r34_dh128](https://github.com/saic-vul/fbrs_interactive_segmentation/blob/master/models/sbd/r34_dh128.py) for an example).

**Comment by humzaahmad906** [comment]
I tried to train the model on sbd dataset and when i ran the following command
__________
python3 train.py models/sbd/r34_dh128.py --gpus=0 --workers=4 --exp-name=first-try
____________
i got
_______
Starting Epoch: 0
Total Epochs: 120
Illegal instruction (core dumped)

**Comment by happyCodingSusan** [comment]
@ptrvilya, thanks for your advice. sbd.py is derived from base.py. In base.py, the function _load_samples_scores will load a "sbd_samples_weights.pkl". What is the purpose of this function and how "sbd_samples_weights.pkl" is generated? Thanks
