### ISSUE TITLE
Assertion Error while running the demo

### ISSUE THREAD

**Issue by tshaark** [saic-vul/fbrs_interactive_segmentation#9]
Traceback (most recent call last):
File "demo.py", line 59, in <module>
    main()
File "demo.py", line 15, in main
    checkpoint_path = utils.find_checkpoint(cfg.INTERACTIVE_MODELS_PATH, args.checkpoint)
  File "/home/tshaark/fbrs_interactive_segmentation/isegm/inference/utils.py", line 173, in find_checkpoint
    assert len(model_checkpoints) == 1
AssertionError

I get this error when I try to run the demo and a similar one when I try to train. Where am I going wrong?

**Comment by ksofiyuk** [comment]
It's most likely that you incorrectly specified the path to the model weights (check `--checkpoint` argument).

**Comment by tshaark** [comment]
Do I have to download the weights for the models I want to use? If so, what should be path of the weights directory?

**Comment by pkraison** [comment]
@tshaark you can download pre-trained weights and put them anywhere. just give the correct path to --checkpoint argument.
--checkpoint=/path to weights/'
